name: Tests

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep $((RANDOM % 15 + 5))
      - run: |
          if [ $((RANDOM % 3)) -eq 0 ]; then
              exit 1
          else
              exit 0
          fi
